Add How to Train in README
IndoNLP/indonlu pull request #2
Opened 2020-09-26 20:44 UTC by atnanahidiw

- Create `scripts/config/model/train.yaml` to easily define the model used
- Make `scripts/trainer.py` and `Makefile` for easy ops

2020-10-06 10:40 UTC, SamuelCahyawijaya requested changes
@gentaiscool : I think we need to change the `load_model` and clean up the unused model checkpoints that are used for our experiment. We can instead use Indobenchmark model in HF as the replacement. Can you help to clean that part?

@atnanahidiw, later you can follow the checkpoint argument based on the finalized models that we have. So it will be cleaner and easier to follow.

2020-10-06 10:40 UTC, SamuelCahyawijaya commented on README.md
> +##### Non Pretrained No Special Token
I think we can remove this one, all no special token experiment is just an experimental before. I feel it will make people confuse.

2020-10-06 14:00 UTC, atnanahidiw commented on README.md
> +##### Non Pretrained No Special Token
removed in the `README.md` kak
but will keep the command in `Makefile` for future reference, normal people don't see it anyway 😛

2020-10-07 08:39 UTC, gentaiscool commented
> @gentaiscool : I think we need to change the `load_model` and clean up the unused model checkpoints that are used for our experiment. We can instead use Indobenchmark model in HF as the replacement. Can you help to clean that part?
> 
> @atnanahidiw, later you can follow the checkpoint argument based on the finalized models that we have. So it will be cleaner and easier to follow.

I will clean the code and add the documentation this week including the CONTRIBUTING page. Let's finish the testing and then, we merge this pull request.

2020-10-09 14:02 UTC, gentaiscool commented
> > @gentaiscool : I think we need to change the `load_model` and clean up the unused model checkpoints that are used for our experiment. We can instead use Indobenchmark model in HF as the replacement. Can you help to clean that part?
> > @atnanahidiw, later you can follow the checkpoint argument based on the finalized models that we have. So it will be cleaner and easier to follow.
> 
> I will clean the code and add the documentation this week including the CONTRIBUTING page. Let's finish the testing and then, we merge this pull request.

I added the CONTRIBUTING page in the `master` branch.

2020-10-10 17:36 UTC, gentaiscool commented
@atnanahidiw we just merged the master branch with a new PR #7. Would you mind to check whether this PR has any conflict?

2020-10-11 09:38 UTC, atnanahidiw commented
hi @gentaiscool, I just resolved all of the conflicts ya, sorry for the late reply 🙏

2020-10-11 09:41 UTC, atnanahidiw commented
> I added the CONTRIBUTING page in the `master` branch.

and thanks also for the [CONTRIBUTING](https://github.com/indobenchmark/indonlu/blob/master/CONTRIBUTING.md) page
should we make it more verbose? ^^a

2020-10-11 14:08 UTC, gentaiscool commented
> > I added the CONTRIBUTING page in the `master` branch.
> 
> and thanks also for the [CONTRIBUTING](https://github.com/indobenchmark/indonlu/blob/master/CONTRIBUTING.md) page
> should we make it more verbose? ^^a

Yes, we should, probably in a new PR?

2020-10-11 14:09 UTC, SamuelCahyawijaya requested changes
@atnanahidiw : We have some update regarding to the model list, can you help removing the unnecessary models and adding the IndoBERT model. I write the comment for all the models that can be removed and also the list of IndoBERT models.

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +# # albert-base-uncased-96000
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +# # albert-base-uncased-96000-spm
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +# - model_checkpoint: albert-base-uncased-96000-spm
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +# # albert-base-uncased-112500-spm
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: scratch
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: babert-base-512
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: babert-bpe-mlm-large-512
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: babert-opensubtitle
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: albert-large-wwmlm-128
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: albert-base-wwmlm-512
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: albert-large-wwmlm-512
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: albert-base-uncased-112500
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: albert-base-uncased-191k
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: cartobert
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: babert-bpe-mlm-large-uncased
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: babert-bpe-mlm-large-uncased-1m
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: babert-bpe-mlm-large-uncased-1100k
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +- model_checkpoint: babert-bpe-mlm-uncased-128-dup10-5
This model can be removed

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on Makefile
> +reproduce_all_1:
We can remove `reproduce_all_*`, it is already covered in `reproduce` and `reproduce_all` for this

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on Makefile
> +run_non_pretrained_no_special_token_all:
There are 8 tasks in here, can you please help adding the other 4 similar to the list in the `reproduce_all`?

2020-10-11 14:09 UTC, SamuelCahyawijaya commented on scripts/config/model/train.yaml
> +    - 12
Can you help adding 8 indoBERT models in this file, the model checkpoint and the num_layers would be as follow:
- indobenchmark/indobert-base-p1 | 12 layers
- indobenchmark/indobert-base-p2 | 12 layers
- indobenchmark/indobert-large-p1 | 24 layers
- indobenchmark/indobert-large-p2 | 24 layers
- indobenchmark/indobert-lite-base-p1 | 12 layers
- indobenchmark/indobert-lite-base-p2 | 12 layers
- indobenchmark/indobert-lite-large-p1 | 24 layers
- indobenchmark/indobert-lite-large-p2 | 24 layers

2020-10-11 14:11 UTC, SamuelCahyawijaya commented
> > > I added the CONTRIBUTING page in the `master` branch.
> > 
> > 
> > and thanks also for the [CONTRIBUTING](https://github.com/indobenchmark/indonlu/blob/master/CONTRIBUTING.md) page
> > should we make it more verbose? ^^a
> 
> Yes, we should, probably in a new PR?

Yeah I agree, this one can be a new PR. Thank you 😀

2025-08-10 03:59 UTC, atnanahidiw commented
seems too old 🙏
let's close this

2025-08-10 03:59 UTC, closed without merging